### ISSUE TITLE
Remove ligatures œ and æ

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/august-strindberg_the-inferno_claud-field#7]
There are quite a few instances of œ and æ throughout (change to oe and ae respectively).

**Comment by robinwhittleton** [comment]
I ran `modernize-spelling` against this which I assumed was enough. @acabal should we be generically removing all instances of œ and æ (at least in English text)?

**Comment by acabal** [comment]
I'm not quite prepared to do that yet... for now let's do it on a case-by-case basis with an eye towards removing them.

**Comment by robinwhittleton** [comment]
OK, let’s keep these, as they seem to be mostly still used with the original spelling:
- Væ soli
- Arcana Cœlestia
- Sacré Cœur
- Jacques Cœur
- Principia Cœli

And let’s change these:
- Hymenæus
- Linnæus
- anæmic
- encyclopædic
- fœtus

Fixed in https://github.com/robinwhittleton/august-strindberg_the-inferno_claud-field/commit/486a96fcc6024a218ba8800b685365f0c6a501a8.
